general = {animations = false}
[[modules_right]]
	name = "system"
	lines = {opengl_version = false, allocation_rate = false, display = false, java_version = false, gpu_driver = false, allocated_memory = false, cpu = false, gpu = false}
	enabled = true
[[modules_right]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_right]]
	name = "target"
    lines = {fluid_tags = false, block_tags = false}
    enabled = true

[[modules_left]]
	name = "fps"
	lines = {fps = true}
	enabled = true
[[modules_left]]
	name = "server"
	lines = {packets_sent = false, packets_received = false, tick_manager_status = false}
	enabled = true
[[modules_left]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_left]]
	name = "coords"
	lines = {absolute_velocity = false, velocity = false, horizontal_velocity = false}
	enabled = true
[[modules_left]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_left]]
	name = "location"
	lines = {day_ticks = false, days_played = false, dimension = false, highest_block = false, highest_block_server = false}
	enabled = true
[[modules_left]]
	name = "entity"
	enabled = true
