name = "1.21.1"
author = "Niodtn"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2fdc366e491bf327eeae14082013120099f283a80de93aaabeeebc622dee06a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
