name = "Create 21"
author = "niodtn"
version = "2025-08-22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fff609a055ed53a683fee92d5116ce913db23801b071e562a21ac1c55800ba75"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"

[options]
datapack-folder = "datapacks"
