name = "Highmint"
author = "Niodtn"
version = "2025-08-18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ff58be66eef7f97e471e64bc83f5ce87c5e95280aecd3fea64df6f2a42e875d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
