name = "Highmint"
author = "Niodtn"
version = "2025-08-17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28e4032f356e12a574a49031b23d0dad449b78f8a6bfc41c515cc9f943ed9832"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
