name = "Niodtn's Modpack 1.21.4"
author = "Niodtn"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c307e292daa5a06d7060b2c3a8841c97ffc4bbb9f36d9b340492a49c64b644f"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
