name = "1.21.1"
author = "Niodtn"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "815208f033963c72cf50478d2430a48bed9c7a6fadd76e800f6bec42e61aaeec"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
