name = "1.21.1"
author = "Niodtn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c22b843a45d532309d20536665e02b0208f2addaafac7f3f2a913e1b35ba30a6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
