name = "1.21.1"
author = "Niodtn"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ab33520dee02dbb436422ceb3b1036ac0a97a7b93c2dab4047d583a5800787f"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
