name = "1.21.1"
author = "Niodtn"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fdce7ee192ed816ff6896dbfe8b63c61a892aa443f58f49de5cebdd19e59960"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
