name = "Mountain"
author = "Niodtn"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90f2accbcf969cb0a18110fd56d5f9e372a7daff875e23c9740b3af1d92d00f2"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.63-beta"
