name = "Mountain"
author = "Niodtn"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc2a13194a87d194d0403e3b128a2b4a01a9697839061410ed92223843928a28"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.63-beta"
