name = "Mountain"
author = "Niodtn"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94a287a9cd67b59564b3f2a024f076136571f3f358b04816990d52b814f0a37d"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.63-beta"
