name = "Mountain"
author = "Niodtn"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cd557a81ad28d1a0054bc9c8ae10c054b6c8cb994084ffd401dd1c5a157488c"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.63-beta"
