name = "RPG 21"
author = "niodtn"
version = "2025-11-18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e57357da168abe473ce3d6513e9a3a5972ea116d27f9041140c252f3793881b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
datapack-folder = "datapacks"
