name = "RPG 21"
author = "niodtn"
version = "2025-11-18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a5b58a2781131c2bcee671ba55ab40e7b21ac9d59b601d76a3a3d7e751df6fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
datapack-folder = "datapacks"
