name = "Niodtn's Modpack 1.21.5"
author = "Niodtn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fc435fed577e927761fe7f6c7f1aa59652affb5cc798b8bb3f1181ea3310049"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
