name = "Niodtn's Modpack 1.21.5"
author = "Niodtn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc71eb3b69f2207745469b7a7493959c26cc9c1dd2692810794bf23bbada716d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
