name = "Niodtn's Modpack 1.21.5"
author = "Niodtn"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ed2f9f98fc175796dcd0bd6c0e3a7357cafb48a992f1205dfc596fddd73f8d0"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
